package webpackparse

import "github.com/teawithsand/handmd/util/simplesite"

const DefaultEntrypointsFile = "entrypoints.json"

// Content of entrypoints.json generated by webpack.
type EntrypointsJSONDoc struct {
	Entrypoints Entrypoints       `json:"entrypoints"`
	Integrity   map[string]string `json:"integrity,omitempty"`
}

// Content of entrypoints.json  generated by webpack.
// More accurrately: contents of it's "entrypoints" filed.
type Entrypoints map[string]Entrypoint

type Entrypoint struct {
	Js  []string `json:"js"`
	Css []string `json:"css"`
}

func (ep Entrypoint) AddToSiteHead(head *simplesite.SiteHead) {

}
